version: '2'
services:
  ishtar-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/ishtar/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ishtar
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
